# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 196e5edb3b5f0274474f2c99809407080bca916ddd9223a353232cc2ebda06b1b32ad79d502a0a7cf40d642e9c01f83d15fcf3db734465986d38b09727b34684

test:
  secret_key_base: 5718bea3778fe142d1238e28a6d412c2b0387c136877a8916cf35cb007a01a14de4a015cf817269a6e3725a9907a6421e85c4f5c04f0b074c257cb4e567329ad

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
